site_name: Documentation

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/icon.png
  palette:
    primary: white
    
extra_css:
  - css/extra.css

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Shared:
      - Charging: shared/charging.md
  - Hardware:
      - WiFi Setup: box/wifi.md
      
