site_name: Training Workx Help Center

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/icon.png
  palette:
    primary: white
    
extra_css:
  - css/extra.css

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Using your box:
      - Whats in the box?: whats-in-the-box.md
      - How to use VR?: how-to-use-vr.md
      - Setting up the guardian?: guardian-setup.md
      - Updating your box: updating-your-box.md
  - Training in VR:
      - Using the spectator: using-the-spectator.md
      - Switching students: switching-students.md
      - Changing languages:  changing-language.md
  - Training Portal:
      - Setting up students: setting-up-students.md 
      - Setting up groups: setting-up-groups.md 
      - Viewing results: viewing-results.md 
      - Using lesson plans: using-lesson-plans.md 
  - Self Installation:
      - Installing the Launcher: installing-the-launcher.md
      - Updating your headset: updating-your-headset.md
      - Adding your own devices: adding-your-own-devices.md 
  - Troubleshooting:
      - Resetting play area: resetting-the-play-area.md 
      - Restarting your headset: restarting-your-headset.md
      - No WiFi: no-wifi.md
      - Controllers not working: controllers-not-working.md
      - Need support?: need-support.md 
      
      
      
      
